name: Publish lambda code to associated ARN.

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy lambda code
        uses: appleboy/lambda-action@v0.1.8
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
          function_name: ${{ secrets.SNS_ALERT_LAMBDA }}
          source: queue-notifications/index.js
